---
train_run_distance: 2E49278L
this_cab_active: 2E4ADEC
atp_worst_case_forward_location: 2E5485AW
atp_worst_case_forward_location_offset: 2E54858W
train_speed: 2E491EEW
line_voltage: 2E4414AW
line_current: 2E4414CW
hscb_close: 2E44CB0
order_hscb_to_open_from_cop: 2E48698
cop_is_ok_for_supervision: 2E46508
mcs_driving_mode_forward: 2E4645A
mcs_driving_mode_inter: 2E46459
mcs_driving_mode_reverse: 2E46458
mcs_driving_mode_protected_manual: 2E4645B
mcs_driving_mode_auto: 2E4647F
mcs_driving_mode_selected: 2E55A2D
actuate_braking: 2E44126
actuate_motor: 2E44127
tr_br_effort_reference_1: 2E450D6W
tr_br_effort_reference_2: 2E450D8W
traction_brake_effort_reference: 2E450CAW
emergency_brake_applied: 2E493EA
brake_cylinder_pressure_car_a_bogie_a: 2E464B6W
brake_cylinder_pressure_car_a_bogie_d: 2E464B8W
brake_cylinder_pressure_car_b_bogie_a: 2E464BAW
brake_cylinder_pressure_car_b_bogie_d: 2E464BCW
brake_cylinder_pressure_car_c_bogie_a: 2E464BEW
brake_cylinder_pressure_car_c_bogie_d: 2E464C0W
brake_cylinder_pressure_car_d_bogie_a: 2E464C2W
brake_cylinder_pressure_car_d_bogie_d: 2E464C4W
main_reservoir_pressure: 2E4CD7CW
wsp_active: 2E464E7
all_doors_closed: 2E4643B
mcm_state: 2E49E30W
traction_brake_achieved: 2E4540CW
actual_chopper_power: 2E49ECCW
actual_motor_power: 2E58A38W
available_dynamic_brake: 2E49E2EW
estimated_brake_resistor_temparature: 2E58B42W
dynamic_brake_ok: 2E45415
lma_end_location: 2E4CFC0W
lma_end_location_offset: 2E4CFC2W
ato_start_button_1_pressed: 2E4645C
ato_start_button_2_pressed: 2E4645D
passesnger_load_car_a: 2E64930W
passesnger_load_car_b: 2E64932W
passesnger_load_car_c: 2E64934W
passesnger_load_car_d: 2E64936W
passenger_load_to_ato: 2E6493CW
compressor_start: 2E60BC2
compressor_motor_running: 2E60BA2
pressure_low_limit: 2E60E5EW
sync_all_clocks: 2E62D14
sync_local_clock: 2E62D15
sync_master_clock_from_pdp1: 2E62D16
sync_master_clock_from_pdp2: 2E62D17
sync_pdp_clock: 2E62D18
year: 2E629C6W
month: 2E629C8W
day: 2E629CAW
hour: 2E629CCW
minute: 2E629CEW
second: 2E629D0W
train_number: 2E54840W
crew_number: 2E54842W
destination_code: 2E54844W
train_service_code: 2E54846W
train_fault_report_code: 2E5484AW
train_stock_type: 2E5484CW
train_unit_number_1st: 2E5484EW
train_unit_number_2nd: 2E54850W
train_mode: 2E54852W
a_car_temperature: 2E63F52W
b_car_temperature: 2E63F54W
c_car_temperature: 2E4CD5CW
d_car_temperature: 2E4CD5AW
pv1_temperature: 2E66C1CW
pv2_temperature: 2E66C1EW
battery_current_sensor: 2E582F6W
