brake_cylinder_pressure:
  - brake_cylinder_pressure_car_a_bogie_a
  - brake_cylinder_pressure_car_a_bogie_d
  - brake_cylinder_pressure_car_b_bogie_a
  - brake_cylinder_pressure_car_b_bogie_d
  - brake_cylinder_pressure_car_c_bogie_a
  - brake_cylinder_pressure_car_c_bogie_d
  - brake_cylinder_pressure_car_d_bogie_a
  - brake_cylinder_pressure_car_d_bogie_d

passenger_load:
  - passesnger_load_car_a
  - passesnger_load_car_b
  - passesnger_load_car_c
  - passesnger_load_car_d
  - passenger_load_to_ato
