walthamstow_central:
  southbound: 37
  northbound: 30
blackhorse_road:
  southbound: 123
  northbound: 128
tottenham_hale:
  southbound: 195
  northbound: 206
seven_sisters:
  southbound: 329
  northbound: 492
finsbury_park:
  southbound: 893
  northbound: 870
highbury_and_islington:
  southbound: 1035
  northbound: 1026
kings_cross_st_pancras:
  southbound: 1193
  northbound: 1174
euston:
  southbound: 1309
  northbound: 1286
warren_street:
  southbound: 1377
  northbound: 1362
oxford_circus:
  southbound: 1463
  northbound: 1430
green_park:
  southbound: 1525
  northbound: 1496
victoria:
  southbound: 1643
  northbound: 1614
pimlico:
  southbound: 1753
  northbound: 1746
  class: normal
vauxhall:
  southbound: 1809
  northbound: 1798
stockwell:
  southbound: 1901
  northbound: 1894
brixton:
  southbound: 2007
  northbound: 1992
